version: '3.3'

services:
  fastapi:
    image: python:3.13.4-slim
    container_name: fastapi
    working_dir: /app
    volumes:
      - ./app:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    expose:
      - 8000

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - fastapi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
